<?php

declare(strict_types=1);

namespace Ledga\Api\Tests\Unit\Services;

use Ledga\Api\Http\HttpClientInterface;
use Ledga\Api\Http\Response;
use Ledga\Api\Resources\Transaction;
use Ledga\Api\Resources\TransactionCode;
use Ledga\Api\Services\TransactionCodeService;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

final class TransactionCodeServiceTest extends TestCase
{
    #[Test]
    public function it_targets_the_trancodes_route(): void
    {
        $http = $this->createMock(HttpClientInterface::class);
        $http->expects($this->once())
            ->method('get')
            ->with('trancodes/tc-1')
            ->willReturn(new Response(200, ['data' => $this->codeData('tc-1', 'INVOICE')]));

        $service = new TransactionCodeService($http);
        $code = $service->get('tc-1');

        $this->assertInstanceOf(TransactionCode::class, $code);
        $this->assertSame('INVOICE', $code->code);
    }

    #[Test]
    public function it_executes_transaction_code_through_envelope(): void
    {
        $http = $this->createMock(HttpClientInterface::class);
        $http->method('post')
            ->with('trancodes/tc-1/execute', ['amount' => '100.00'])
            ->willReturn(new Response(201, ['data' => $this->transactionData()]));

        $service = new TransactionCodeService($http);
        $tx = $service->execute('tc-1', ['amount' => '100.00']);

        $this->assertInstanceOf(Transaction::class, $tx);
        $this->assertSame('tx-1', $tx->id);
    }

    /**
     * @return array<string, mixed>
     */
    private function codeData(string $id, string $code): array
    {
        return [
            'id' => $id,
            'ledger_id' => 'ledger-1',
            'code' => $code,
            'name' => 'Invoice',
            'description' => null,
            'status' => 'active',
            'version' => 1,
            'params_schema' => null,
            'entries_template' => [],
            'validation_rules' => null,
            'metadata' => null,
            'created_at' => '2025-01-01T12:00:00Z',
            'updated_at' => '2025-01-01T12:00:00Z',
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function transactionData(): array
    {
        return [
            'id' => 'tx-1',
            'ledger_id' => 'ledger-1',
            'journal_id' => null,
            'reference' => null,
            'description' => 'Generated by tc-1',
            'effective_date' => '2025-01-01T12:00:00Z',
            'layer' => 'SETTLED',
            'status' => 'posted',
            'total_amount' => '100.00',
            'entry_count' => 2,
            'hash' => null,
            'previous_hash' => null,
            'correlation_id' => null,
            'metadata' => null,
            'original_transaction_id' => null,
            'reversal_reason' => null,
            'entries' => [],
            'created_at' => '2025-01-01T12:00:00Z',
            'updated_at' => '2025-01-01T12:00:00Z',
        ];
    }
}
